# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven On self-hosted runner

on:
  issue_comment:
    types: [created]

jobs:
  build:
    permissions: write-all
    # check if the comments come from pull request, exclude those from issue && check if it contains a specific comment
    if: contains(github.event.comment.html_url, '/pull/') && github.event.issue.pull_request && contains(github.event.comment.body, '/self-hosted-runner')
    # && (github.actor == 'tommaso-borgato')
    runs-on: 
    - self-hosted
    - jakarta-sample-app

    steps:    
    - id: enforce-collaborator-action
      uses: tommaso-borgato/enforce-collaborator-action@1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: is collaborator
      if: ${{ ! steps.enforce-collaborator-action.outputs.is-collaborator }}
      run: |
        echo "${{ github.triggering_actor }} cannot run this workflow!"
        exit 1
    - uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.comment-branch.outputs.head_ref }}
    - name: Build with Maven
      run: mvn -B package
    - name: Set latest commit status as ${{ job.status }}
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        sha: ${{ steps.comment-branch.outputs.head_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        description: "Internal CI: OK (author: ${{ github.event.comment.author }}, editor: ${{ github.event.comment.editor }})"
